### ISSUE TITLE
Minecraft does not start.

### ISSUE THREAD

**Issue by lex1975** [Tfarcenim/HarvestCraftTweaker2#4]
Minecraft does not start.
Included mods: 

CraftTweaker2-1.12-4.1.20.586.jar
harvestcrafttweaker-1.2c.jar
Pam's+HarvestCraft+1.12.2zg.jar

forge:1.12.2-14.23.5.2855

latest.log:
---------------------------
[06:28:37] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[06:28:37] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[06:28:37] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[06:28:38] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2855 for Minecraft 1.12.2 loading
[06:28:38] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_281, running on Windows 7:amd64:6.1, installed at C:\Program Files\Java\jre1.8.0_281
[06:28:38] [main/INFO] [FML]: Searching D:\prog\Minecraft\MC-112\MC1\mods for mods
[06:28:38] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from harvestcrafttweaker-1.2c.jar
[06:28:38] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[06:28:38] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[06:28:38] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.ClassNotFoundException: org.spongepowered.asm.launch.MixinTweaker
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_281]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_281]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_281]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[06:28:38] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[06:28:38] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[06:28:38] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[06:28:38] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[06:28:38] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[06:28:38] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[06:28:38] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

debug.log:
-----------------------------
[06:28:37] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[06:28:37] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[06:28:37] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[06:28:38] [main/DEBUG] [FML]: Injecting tracing printstreams for STDOUT/STDERR.
[06:28:38] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2855 for Minecraft 1.12.2 loading
[06:28:38] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_281, running on Windows 7:amd64:6.1, installed at C:\Program Files\Java\jre1.8.0_281
[06:28:38] [main/DEBUG] [FML]: Java classpath at launch is:
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\net\minecraftforge\forge\1.12.2-14.23.5.2855\forge-1.12.2-14.23.5.2855.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\org\ow2\asm\asm-debug-all\5.2\asm-debug-all-5.2.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\net\minecraft\launchwrapper\1.12\launchwrapper-1.12.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\org\jline\jline\3.5.1\jline-3.5.1.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\com\typesafe\akka\akka-actor_2.11\2.3.3\akka-actor_2.11-2.3.3.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\com\typesafe\config\1.2.1\config-1.2.1.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\org\scala-lang\scala-actors-migration_2.11\1.1.0\scala-actors-migration_2.11-1.1.0.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\org\scala-lang\scala-compiler\2.11.1\scala-compiler-2.11.1.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\org\scala-lang\plugins\scala-continuations-library_2.11\1.0.2_mc\scala-continuations-library_2.11-1.0.2_mc.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\org\scala-lang\plugins\scala-continuations-plugin_2.11.1\1.0.2_mc\scala-continuations-plugin_2.11.1-1.0.2_mc.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\org\scala-lang\scala-library\2.11.1\scala-library-2.11.1.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\org\scala-lang\scala-parser-combinators_2.11\1.0.1\scala-parser-combinators_2.11-1.0.1.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\org\scala-lang\scala-reflect\2.11.1\scala-reflect-2.11.1.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\org\scala-lang\scala-swing_2.11\1.0.1\scala-swing_2.11-1.0.1.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\org\scala-lang\scala-xml_2.11\1.0.2\scala-xml_2.11-1.0.2.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\lzma\lzma\0.0.1\lzma-0.0.1.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\java3d\vecmath\1.5.2\vecmath-1.5.2.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\net\sf\trove4j\trove4j\3.0.3\trove4j-3.0.3.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\org\apache\maven\maven-artifact\3.5.3\maven-artifact-3.5.3.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\net\sf\jopt-simple\jopt-simple\5.0.3\jopt-simple-5.0.3.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\oshi-project\oshi-core\1.1\oshi-core-1.1.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\net\java\dev\jna\jna\4.4.0\jna-4.4.0.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\net\java\dev\jna\platform\3.4.0\platform-3.4.0.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\io\netty\netty-all\4.1.9.Final\netty-all-4.1.9.Final.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\com\google\guava\guava\21.0\guava-21.0.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\org\apache\commons\commons-lang3\3.5\commons-lang3-3.5.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\commons-io\commons-io\2.5\commons-io-2.5.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\commons-codec\commons-codec\1.10\commons-codec-1.10.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\com\google\code\gson\gson\2.8.0\gson-2.8.0.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\com\mojang\authlib\1.5.25\authlib-1.5.25.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\com\mojang\realms\1.10.22\realms-1.10.22.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\it\unimi\dsi\fastutil\7.1.0\fastutil-7.1.0.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\org\apache\logging\log4j\log4j-api\2.8.1\log4j-api-2.8.1.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\org\apache\logging\log4j\log4j-core\2.8.1\log4j-core-2.8.1.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\org\lwjgl\lwjgl\lwjgl\2.9.4-nightly-20150209\lwjgl-2.9.4-nightly-20150209.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.4-nightly-20150209\lwjgl_util-2.9.4-nightly-20150209.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\libraries\com\mojang\text2speech\1.10.3\text2speech-1.10.3.jar
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\versions\Forge 1.12.2\Forge 1.12.2.jar
[06:28:38] [main/DEBUG] [FML]: Java library path at launch is:
[06:28:38] [main/DEBUG] [FML]:     D:\prog\Minecraft\MC-112\MC1\versions\Forge 1.12.2\natives
[06:28:38] [main/DEBUG] [FML]: Determined Minecraft Libraries Root: D:\prog\Minecraft\MC-112\MC1\libraries
[06:28:38] [main/DEBUG] [FML]: Cleaning up mods folder: D:\prog\Minecraft\MC-112\MC1\mods
[06:28:38] [main/DEBUG] [FML]: Examining file: CraftTweaker2-1.12-4.1.20.586.jar
[06:28:38] [main/DEBUG] [FML]: Examining file: harvestcrafttweaker-1.2c.jar
[06:28:38] [main/DEBUG] [FML]: Examining file: Pam's+HarvestCraft+1.12.2zg.jar
[06:28:38] [main/DEBUG] [FML]: Enabling runtime deobfuscation
[06:28:38] [main/DEBUG] [FML]: Instantiating coremod class FMLCorePlugin
[06:28:38] [main/DEBUG] [FML]: Found signing certificates for coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin)
[06:28:38] [main/DEBUG] [FML]: Found certificate e3c3d50c7c986df74c645c0ac54639741c90a557
[06:28:38] [main/DEBUG] [FML]: Added access transformer class net.minecraftforge.fml.common.asm.transformers.AccessTransformer to enqueued access transformers
[06:28:38] [main/DEBUG] [FML]: Enqueued coremod FMLCorePlugin
[06:28:38] [main/DEBUG] [FML]: Instantiating coremod class FMLForgePlugin
[06:28:38] [main/DEBUG] [FML]: Found signing certificates for coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin)
[06:28:38] [main/DEBUG] [FML]: Found certificate e3c3d50c7c986df74c645c0ac54639741c90a557
[06:28:38] [main/DEBUG] [FML]: Enqueued coremod FMLForgePlugin
[06:28:38] [main/DEBUG] [FML]: All fundamental core mods are successfully located
[06:28:38] [main/DEBUG] [FML]: Discovering coremods
[06:28:38] [main/INFO] [FML]: Searching D:\prog\Minecraft\MC-112\MC1\mods for mods
[06:28:38] [main/DEBUG] [FML]:   Adding CraftTweaker2-1.12-4.1.20.586.jar to the mod list
[06:28:38] [main/DEBUG] [FML]:   Adding harvestcrafttweaker-1.2c.jar to the mod list
[06:28:38] [main/DEBUG] [FML]:   Adding Pam's+HarvestCraft+1.12.2zg.jar to the mod list
[06:28:38] [main/DEBUG] [FML]: Examining for coremod candidacy CraftTweaker2-1.12-4.1.20.586.jar
[06:28:38] [main/DEBUG] [FML]: Not found coremod data in CraftTweaker2-1.12-4.1.20.586.jar
[06:28:38] [main/DEBUG] [FML]: Examining for coremod candidacy harvestcrafttweaker-1.2c.jar
[06:28:38] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from harvestcrafttweaker-1.2c.jar
[06:28:38] [main/DEBUG] [FML]: Examining for coremod candidacy Pam's+HarvestCraft+1.12.2zg.jar
[06:28:38] [main/DEBUG] [FML]: Not found coremod data in Pam's+HarvestCraft+1.12.2zg.jar
[06:28:38] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[06:28:38] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[06:28:38] [main/ERROR] [LaunchWrapper]: Unable to launch
java.lang.ClassNotFoundException: org.spongepowered.asm.launch.MixinTweaker
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_281]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:106) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_281]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_281]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_281]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[06:28:38] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
[06:28:38] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)
[06:28:38] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)
[06:28:38] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)
[06:28:38] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)
[06:28:38] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
[06:28:38] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by lex1975** [comment]
If I try to load the entire assembly (142 mods) with your mod, I get an error while loading:
--------------------------------
// I feel sad now :(

Time: 3/2/21 7:01 AM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at net.minecraftforge.fml.common.versioning.ComparableVersion.parseVersion(ComparableVersion.java:390)
	at net.minecraftforge.fml.common.versioning.ComparableVersion.<init>(ComparableVersion.java:381)
	at net.minecraftforge.fml.common.versioning.DefaultArtifactVersion.<init>(DefaultArtifactVersion.java:31)
	at net.minecraftforge.fml.common.versioning.DefaultArtifactVersion.<init>(DefaultArtifactVersion.java:42)
	at net.minecraftforge.fml.common.FMLModContainer.getProcessedVersion(FMLModContainer.java:651)
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:243)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:572)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.fml.common.versioning.ComparableVersion.parseVersion(ComparableVersion.java:390)
	at net.minecraftforge.fml.common.versioning.ComparableVersion.<init>(ComparableVersion.java:381)
	at net.minecraftforge.fml.common.versioning.DefaultArtifactVersion.<init>(DefaultArtifactVersion.java:31)
	at net.minecraftforge.fml.common.versioning.DefaultArtifactVersion.<init>(DefaultArtifactVersion.java:42)
	at net.minecraftforge.fml.common.FMLModContainer.getProcessedVersion(FMLModContainer.java:651)
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:243)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:572)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:232)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_281, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 149092944 bytes (142 MB) / 361283584 bytes (344 MB) up to 12364808192 bytes (11792 MB)

**Comment by Tfarcenim** [comment]
install mixinbootstrap

**Comment by lex1975** [comment]
Dear mod author! Please add to the description a requirement to install the 'MixinBootstrap' library. Or add a dependency line to 'mcmod.info', for example: '"dependencies": ["mixinbootstrap"]'

**Comment by Tfarcenim** [comment]
It's not that easy, if I add a hard requirement, the game will crash when other mixin packaging mods are installed.

**Comment by Tfarcenim** [comment]
MixinBootstrap is only to be used when it is confirmed that no other mods package Mixin.
